import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import React from "react";
import {languages} from "@/locale/settings";
import {Providers} from "@/app/providers";
import {Lang, getDictionary} from "@/dictionaries/get-dictionary";
import ChakraLayout from "@/app/[lang]/ChakraLayout";
import './globals.css'


const inter = Inter({subsets: ['latin']})

export async function generateStaticParams() {
  return languages.map((lang) => ({lang}))
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default async function RootLayout(
  {
    children,
    params: {lang},
  }: {
    children: React.ReactNode
    params: { lang: Lang }
  }) {
  const dict = await getDictionary(lang)
  return (
    <html lang={lang}>
    <body className={inter.className}>
    <Providers dict={dict} lang={lang}>
      <ChakraLayout>
        {children}
      </ChakraLayout>
    </Providers>
    </body>
    </html>
  )
}
