import type {Metadata} from 'next'
import {Roboto} from 'next/font/google'
import React from "react";
import {languages} from "@/locale/settings";
import {Providers} from "@/app/providers";
import {getDictionary, Lang} from "@/dictionaries/get-dictionary";
import './globals.scss'
import Container from "@/components/Container";
import {Brand} from "@/schemas/brands";

const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export async function generateStaticParams() {
  return languages.map((lang) => ({lang}))
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

async function getBrands(): Promise<Brand[]> {
  const result = await fetch('https://mirobuvi.com.ua/xml_ftp/brands.json')
  if (!result.ok) {
    throw new Error('Fail to fetch brands data')
  }
  return result.json()
}

export default async function RootLayout(
  {
    children,
    params: {lang},
  }: {
    children: React.ReactNode
    params: { lang: Lang }
  }) {
  const dict = await getDictionary(lang)
  const brands = await getBrands()
  return (
    <html lang={lang}>
    <body className={roboto.className}>
    <Providers dict={dict} lang={lang}>
      <Container brands={brands}>
        {children}
      </Container>
    </Providers>
    </body>
    </html>
  )
}
