import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from "react";
import {languages} from "@/app/locale/settings";



const inter = Inter({ subsets: ['latin'] })
export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }))
}
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
interface Params {
  lng: string
}

interface Props {
  children: React.ReactNode
  params: Params
}

export default function RootLayout({ children, params: {lng}}: Props) {
  return (
    <html lang={lng}>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
